### ISSUE TITLE
Open/close reversed in HomeKit

### ISSUE THREAD

**Issue by roddenshaw** [SwitchBot/homebridge-switchbot-ble#5]
I have gotten this plugin working with Hoobs, which is great. Unfortunately I find that ‘closed’ in HomeKit opens the curtains and vice versa.

**Comment by roddenshaw** [comment]
Thanks for updating this. I tried the new parameter (both true and false) and it made no difference. Tried uninstalling and reinstalling the plugin too, but whether I set ‘true’ or ‘false’ I still try the same inverted position.

**Comment by SwitchBot-Wonderlabs** [comment]
> Thanks for updating this. I tried the new parameter (both true and false) and it made no difference. Tried uninstalling and reinstalling the plugin too, but whether I set ‘true’ or ‘false’ I still try the same inverted position.

Hi, roddenshaw, the newest plug-in has not yet been released to NPM.

**Comment by SwitchBot-Wonderlabs** [comment]
Hey, @roddenshaw , V1.2.0 is released.
