### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by samsonrosen** [SwitchBot/homebridge-switchbot-ble#6]
Hi,

The plug-in I’ve been using for my SwitchBot is amazing:

https://github.com/zizi4n5/homebridge-switchbot-for-mac

A really useful feature they implemented was state set by pinging an IP address. The context is a wireless printer so the switchbot displays as on in HomeKit if the printer is switched on and pingable etc.

Are you able to implement this feature? It would be useful for anything with network connectivity.

Thanks,

Sam

**Comment by SwitchBot-Wonderlabs** [comment]
I’ve seen it before, and it’s a good idea.
But this feature is not related to this project.
It should be to develop a PING plug-in, and use HomeKit or other platforms to automate.
