### ISSUE TITLE
Request for using the node-switchbot method to add sensor readings

### ISSUE THREAD

**Issue by zeroecho** [SwitchBot/homebridge-switchbot-ble#9]
@SwitchBot-Wonderlabs @SwitchBot Possibly a stupid question but given that this exists and claims to be able to read the meter values and is written in node.js https://www.npmjs.com/package/node-switchbot

Would it be possible to quickly add it to this project? I see you focused on bot and curtain first which is obviously the top priority. I was hoping given there’s an existing way in node and you’ve already got the BLE function written in your plugin, to expose the sensor values that it might not be a quick win? 

Would give those of us wanting to use temperature and humidity sensors with our other HomeKit gear a path forward.

Thanks again for all the teams hard work, I’ve found your support teams to be a breath of fresh air compared to all the other tech companies I’ve dealt with recent (including Apple who have not resolved issues that last 3 times I’ve spoke to them. You guys rock!)

Can’t wait for my curtains to arrive hopefully in the next two weeks and starting adding those into my HA setup!

**Comment by SwitchBot-Wonderlabs** [comment]
@zeroecho V1.2.1 Get temperature and humidity from Meter advertising periodically.

**Comment by zeroecho** [comment]
Upgraded and can see the sensors now but showing as 0% and 0C on two different sensors. Any ideas? Tried upping the scan duration from the stock values in the instructions page to no avail.

![D1B9DA22-A3A4-4D51-B8C4-948885983AED](https://user-images.githubusercontent.com/2373897/98992807-862c4d00-2525-11eb-90e3-1f843fb76505.jpeg)
![E7B201EF-F37D-47CB-A129-B746DED582FE](https://user-images.githubusercontent.com/2373897/98992810-875d7a00-2525-11eb-8e6a-7c8806f5bd5d.jpeg)

**Comment by SwitchBot-Wonderlabs** [comment]
Hi, @zeroecho ，
Are you using Raspberry Pi?
Is the Meter near the scan device?
What are the scanDuration and scanInterval in the config file?
